const items = [
    { title: "Obys", tag: ["mix"], img: "../assets/work/img6.jpg", link: "./showcase/obys/index.html" },
    { title: "Rejouice", tag: ["mix"], img: "../assets/work/img1.jpg", link: "./showcase/rejouice/index.html" },
    { title: "Dribbble", tag: ["mix"], img: "../assets/work/img12.jpg", link: "./showcase/dribbble/index.html" },    
    { title: "Sundown", tag: ["mix"], img: "../assets/work/img9.jpg", link: "./showcase/sundown/index.html" },
    { title: "Premier", tag: ["mix"], img: "../assets/work/img4.jpg", link: "./showcase/premier/index.html" },
    { title: "Business Dashboard", tag: ["mix"], img: "../assets/work/img25.jpg", link: "./showcase/corporate/index.html" },
    { title: "Two Good Co", tag: ["mix"], img: "../assets/work/img14.jpg", link: "./showcase/two-good-co/index.html" },
    { title: "Fashion Week", tag: ["mix"], img: "../assets/work/img17.jpg", link: "./showcase/fashion-week/index.html" },
    { title: "Sidcup Family Golf", tag: ["mix"], img: "../assets/work/img16.jpg", link: "./showcase/sidcup-family-golf/index.html" },
    { title: "Curing Alert", tag: ["mix"], img: "../assets/work/img23.jpg", link: "./showcase/corporate/index.html" },
    { title: "The Plug", tag: ["mix"], img: "../assets/work/img20.jpg", link: "./showcase/the-plug/index.html" },
    { title: "Learning App", tag: ["mix"], img: "../assets/work/img31.jpg", link: "./showcase/corporate/index.html" },

    { title: "Rejouice", tag: ["recreate"], img: "../assets/work/img26.jpg", link: "./showcase/rejouice/index.html" },
    { title: "Premier", tag: ["recreate"], img: "../assets/work/img24.jpg", link: "./showcase/premier/index.html" },
    { title: "Obys", tag: ["recreate"], img: "../assets/work/img21.jpg", link: "./showcase/obys/index.html" },
    { title: "Sundown", tag: ["recreate"], img: "../assets/work/img19.jpg", link: "./showcase/obys/sundown.html" },
    { title: "Dribbble", tag: ["recreate"], img: "../assets/work/img15.jpg", link: "./showcase/dribbble/index.html" },
    { title: "Two Good Co", tag: ["recreate"], img: "../assets/work/img2.jpg", link: "./showcase/two-good-co/index.html" },
    { title: "Sidcup Family Golf", tag: ["recreate"], img: "../assets/work/img11.jpg", link: "./showcase/sidcup-family-golf/index.html" },
    { title: "Fashion Week", tag: ["recreate"], img: "../assets/work/img7.jpg", link: "./showcase/fashion-week/index.html" },
    { title: "The Plug", tag: ["recreate"], img: "../assets/work/img5.jpg", link: "./showcase/the-plug/index.html" },

    { title: "Curing Alert", tag: ["corporate"], img: "../assets/work/img3.jpg", link: "./showcase/corporate/index.html" },
    { title: "Business Dashboard", tag: ["corporate"], img: "../assets/work/img8.jpg", link: "./showcase/corporate/index.html" },
    { title: "Learning App", tag: ["corporate"], img: "../assets/work/img10.jpg", link: "./showcase/corporate/index.html" },
  ];