const items = [
    { title: "Obys", tag: ["mix"], img: "../assets/work/img6.jpg" },
    { title: "Rejouice", tag: ["mix"], img: "../assets/work/img1.jpg" },
    { title: "Dribbble", tag: ["mix"], img: "../assets/work/img12.jpg" },    
    { title: "Sundown", tag: ["mix"], img: "../assets/work/img9.jpg" },
    { title: "Premier", tag: ["mix"], img: "../assets/work/img4.jpg" },
    { title: "Business Dashboard", tag: ["mix"], img: "../assets/work/img25.jpg" },
    { title: "Two Good Co", tag: ["mix"], img: "../assets/work/img14.jpg" },
    { title: "Fashion Week", tag: ["mix"], img: "../assets/work/img17.jpg" },
    { title: "Sidcup Family Golf", tag: ["mix"], img: "../assets/work/img16.jpg" },
    { title: "Curing Alert", tag: ["mix"], img: "../assets/work/img23.jpg" },
    { title: "The Plug", tag: ["mix"], img: "../assets/work/img20.jpg" },
    { title: "Learning App", tag: ["mix"], img: "../assets/work/img31.jpg" },

    { title: "Rejouice", tag: ["recreate"], img: "../assets/work/img26.jpg" },
    { title: "Premier", tag: ["recreate"], img: "../assets/work/img24.jpg" },
    { title: "Obys", tag: ["recreate"], img: "../assets/work/img21.jpg" },
    { title: "Sundown", tag: ["recreate"], img: "../assets/work/img19.jpg" },
    { title: "Dribbble", tag: ["recreate"], img: "../assets/work/img15.jpg" },
    { title: "Two Good Co", tag: ["recreate"], img: "../assets/work/img2.jpg" },
    { title: "Sidcup Family Golf", tag: ["recreate"], img: "../assets/work/img11.jpg" },
    { title: "Fashion Week", tag: ["recreate"], img: "../assets/work/img7.jpg" },
    { title: "The Plug", tag: ["recreate"], img: "../assets/work/img5.jpg" },

    { title: "Curing Alert", tag: ["corporate"], img: "../assets/work/img3.jpg" },
    { title: "Business Dashboard", tag: ["corporate"], img: "../assets/work/img8.jpg" },
    { title: "Learning App", tag: ["corporate"], img: "../assets/work/img10.jpg" },
  ];