const items = [
    { title: "Obys", tag: ["mix"], img: "../assets/work/img1.png", link: "./showcase/obys/index.html" },
    { title: "Rejouice", tag: ["mix"], img: "../assets/work/img2.png", link: "./showcase/rejouice/index.html" },
    { title: "Dribbble", tag: ["mix"], img: "../assets/work/img3.png", link: "./showcase/dribbble/index.html" },    
    { title: "Sundown", tag: ["mix"], img: "../assets/work/img4.png", link: "./showcase/sundown/index.html" },
    { title: "Premier", tag: ["mix"], img: "../assets/work/img5.png", link: "./showcase/premier/index.html" },
    { title: "Business Dashboard", tag: ["mix"], img: "../assets/work/img6.png", link: "./showcase/corporate/index.html" },
    { title: "Two Good Co", tag: ["mix"], img: "../assets/work/img7.png", link: "./showcase/two-good-co/index.html" },
    { title: "Fashion Week", tag: ["mix"], img: "../assets/work/img8.png", link: "./showcase/fashion-week/index.html" },
    { title: "Sidcup Family Golf", tag: ["mix"], img: "../assets/work/img9.png", link: "./showcase/sidcup-family-golf/index.html" },
    { title: "Curing Alert", tag: ["mix"], img: "../assets/work/img10.png", link: "./showcase/corporate/index.html" },
    { title: "The Plug", tag: ["mix"], img: "../assets/work/img11.png", link: "./showcase/the-plug/index.html" },
    { title: "Learning App", tag: ["mix"], img: "../assets/work/img12.png", link: "./showcase/corporate/index.html" },

    { title: "Rejouice", tag: ["recreate"], img: "../assets/work/img2.png", link: "./showcase/rejouice/index.html" },
    { title: "Premier", tag: ["recreate"], img: "../assets/work/img5.png", link: "./showcase/premier/index.html" },
    { title: "Obys", tag: ["recreate"], img: "../assets/work/img1.png", link: "./showcase/obys/index.html" },
    { title: "Sundown", tag: ["recreate"], img: "../assets/work/img4.png", link: "./showcase/obys/sundown.html" },
    { title: "Dribbble", tag: ["recreate"], img: "../assets/work/img3.png", link: "./showcase/dribbble/index.html" },
    { title: "Two Good Co", tag: ["recreate"], img: "../assets/work/img7.png", link: "./showcase/two-good-co/index.html" },
    { title: "Sidcup Family Golf", tag: ["recreate"], img: "../assets/work/img9.png", link: "./showcase/sidcup-family-golf/index.html" },
    { title: "Fashion Week", tag: ["recreate"], img: "../assets/work/img8.png", link: "./showcase/fashion-week/index.html" },
    { title: "The Plug", tag: ["recreate"], img: "../assets/work/img11.png", link: "./showcase/the-plug/index.html" },

    { title: "Curing Alert", tag: ["corporate"], img: "../assets/work/img10.png", link: "./showcase/corporate/index.html" },
    { title: "Business Dashboard", tag: ["corporate"], img: "../assets/work/img6.png", link: "./showcase/corporate/index.html" },
    { title: "Learning App", tag: ["corporate"], img: "../assets/work/img12.png", link: "./showcase/corporate/index.html" },
  ];